[tool.yapf]
based_on_style = "yapf"

[tool.pytype]
# TODO(levskaya): figure out why we get pyi-error from flax's root __init__.py
# could be a pytype bug.
disable = "pyi-error"

[tool.mypy]
show_error_codes = true
no_implicit_optional = true
disable_error_code = "attr-defined"

[[tool.mypy.overrides]]
module = [
    "mypy-tensorflow.*",
    "mypy-tensorboard.*",
    "mypy-absl.*",
    "mypy-jaxlib.cuda.*",
    "mypy-jaxlib.cpu.*",
    "mypy-msgpack",
    "mypy-numpy.*",
    "mypy-optax.*",
    "mypy-orbax.*",
    "mypy-opt_einsum.*",
    "mypy-scipy.*",
    "mypy-libtpu.*",
    "mypy-jaxlib.mlir.*",
    "mypy-yaml",
]
ignore_missing_imports = true

[tool.pytest.ini_options]
filterwarnings = [
    # By default error out on any warnings.
    "error",
    # Jax warning when no gpu/tpu found.
	"ignore:No GPU/TPU found, falling back to CPU.*:UserWarning",
    # We should remove our dependence on jtu.
    "ignore:jax.test_util.check_eq is deprecated and will soon be removed.*:FutureWarning",
    # ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
    "ignore:can't resolve package from.*:ImportWarning",
    # traverse_util.Traversal will be removed soon.
    "ignore:`flax.traverse_util.Traversal` will be deprecated.*:DeprecationWarning",
    # distutils DeprecationWarning
    "ignore:distutils Version classes are deprecated.*:DeprecationWarning",
    # Deprecated numpy for Python 3.9
    "ignore:`np.bool.*` is a deprecated alias:DeprecationWarning",
    "ignore:NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays:DeprecationWarning",
]

[tool.coverage.report]
exclude_lines = [
    "@abc.abstractmethod",
    "raise NotImplementedError",
]
